<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
	  <LangVersion>latest</LangVersion>
	  <Nullable>enable</Nullable>
	  <WarningsAsErrors>nullable</WarningsAsErrors>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Copyright>Copyright (c) 2020-2026 MetaFac</Copyright>
	  <Company>MetaFac</Company>
	  <Authors>MetaFac Contributors</Authors>
	  <Product>Standard</Product>
	  <Description>RFC 4648 codecs</Description>
	  <Title>MetaFac.Standard</Title>
	  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	  <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <SignAssembly>True</SignAssembly>
	  <AssemblyOriginatorKeyFile>..\SigningKey.snk</AssemblyOriginatorKeyFile>
	  <IncludeSymbols>true</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <PackageProjectUrl>https://github.com/metafac-net/RFC4648</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/metafac-net/RFC4648</RepositoryUrl>
	  <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>

</Project>
