<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net481;net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="Multiformats.Base" Version="2.0.2" />
		<PackageReference Include="Shouldly" Version="4.3.0" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="10.1.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MetaFac.Standard.RFC4648\MetaFac.Standard.RFC4648.csproj" />
	</ItemGroup>

</Project>
